openapi: 3.0.0
info:
  title: OnMars
  description: Documentação da API desenvolvida no projeto [OnMars](https://github.com/GiovanniHessel94/project-on-mars)
  version: 0.0.1
servers:
  - url: https://project-on-mars.gigalixirapp.com/api/
    description: Servidor "produção" sendo executado na plataforma gigalixir
  - url: http://localhost:4000/api
    description: Servidor aberto após executar a aplicação localmente
paths:
  /rovers/coordinates:
    get:
      description: Retorna a posição atual da sonda nos eixos x e y, e a letra inicial de sua direção, sendo esta "E - Esquerda", "D - Direita", "C - Cima" ou "B - Baixo"
      responses:
        '200':
          description: Dados de posição da sonda obtidos com sucesso
          content:
            application/json:
              schema: 
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      direction:
                        type: string
                        description: Direção atual da sonda
                        example: "D"
                      x:
                        type: number
                        description: Posição da sonda no eixo x
                        example: 0
                      y:
                        type: number
                        description: Posição da sonda no eixo y
                        example: 0
                  message:
                    type: string
                    description: mensagem de sucesso
                    example: Coordenatas obtidas com sucesso!
  /rovers/execute:
    post:
      description: Executa a série de comandos recebidos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commands:
                  type: array
                  example: ["GE", "M", "M"]
                  items:
                    type: string
                    description: Comando a ser executado. GE, GD ou M
                    enum: ["GE", "GD", "M"]
      responses:
        '200':
          description: Posição da sonda após execução dos comandos com sucesso
          content:
            application/json:
              schema: 
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      x:
                        type: number
                        description: Posição da sonda no eixo x
                        example: 0
                      y:
                        type: number
                        description: Posição da sonda no eixo y
                        example: 0
                  message:
                    type: string
                    description: mensagem de sucesso
                    example: Comandos executados com sucesso!
        '400':
          description: Os comandos não informados, foram recebidos comandos inválidos ou a série de comandos não pode ser executada pois a sonda acabaria fora do quadrante permitido
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CommandsRequired'
                  - $ref: '#/components/schemas/InvalidCommands'
                  - $ref: '#/components/schemas/InvalidCommandsSequence'
              examples:
                CommandsRequiredExample:
                  $ref: '#/components/examples/CommandsRequiredExample'
                InvalidCommandsExample:
                  $ref: '#/components/examples/InvalidCommandsExample'
                InvalidCommandsSequenceExample:
                  $ref: '#/components/examples/InvalidCommandsSequenceExample'
  /rovers/reset:
    put:
      description: Retorna a sonda para posição e estado inicial onde x é 0, y é 0 e sua direção é "D - Direita"
      responses:
        '204':
          description: Sonda retornada para posição e estado inicial com sucesso
components:
  examples:
    CommandsRequiredExample:
      value:
        error: 
          commands: [A lista de comandos é obrigatória e deve conter um ou mais comandos! Verifique o corpo da requisição.]
      summary: Comandos não informados
    InvalidCommandsExample:
      value:
        error: 
          commands: [Foram identificados comandos inválidos! Verifique os comandos enviados.]
      summary: Comandos inválidos na requisição
    InvalidCommandsSequenceExample:
      value:
        error: A sonda detectou que essa série de comandos não pode ser executada!
      summary: Série de comandos não pode ser executada
  schemas:
    CommandsRequired:
      type: object
      properties:
        error:
          type: object
          properties:
            commands:
              type: array
              items:
                type: string
                description: mensagem de erro
                example: A lista de comandos é obrigatória! Verifique o corpo da requisição.
    InvalidCommands:
      type: object
      properties:
        error:
          type: object
          properties:
            commands:
              type: array
              items:
                type: string
                description: mensagem de erro
                example: Foram identificados comandos inválidos! Verifique os comandos enviados.
    InvalidCommandsSequence:
          type: object
          properties:
            error:
              type: string
              description: mensagem de erro
              example: A sonda detectou que essa série de comandos não pode ser executada!